package com.topic.controller;

import com.topic.util.exeptions.NotImplementedException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.kafka.core.KafkaAdmin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class DebugController {

    @Autowired
    private KafkaAdmin kafkaAdmin;

    @GetMapping("/hello")
    public String hello() {
        return "hello!";
    }

//    Autogenerated
    @GetMapping("/test-kafka")
    public String test() {
        try {
            kafkaAdmin.describeTopics().keySet();
            return "Kafka подключена!";
        } catch (Exception e) {
            return "Ошибка подключения: " + e.getMessage();
        }
    }

}
