package com.topic.controller;

import com.topic.util.annotations.Logging;
import com.topic.util.exeptions.NotImplementedException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.data.redis.core.StringRedisTemplate;
import org.springframework.kafka.core.KafkaAdmin;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class DebugController {

    @Autowired
    private KafkaAdmin kafkaAdmin;

    @Autowired
    private StringRedisTemplate redisTemplate;

    @GetMapping("/hello")
    public String hello() {
        return "hello!";
    }

//    Autogenerated
    @GetMapping("/test-kafka")
    @Logging
    public String testKafka() {
        try {
            kafkaAdmin.describeTopics();
            return "Kafka подключена!";
        } catch (Exception e) {
            return "Ошибка подключения: " + e.getMessage();
        }
    }

    @GetMapping("/test-redis")
    @Logging
    public String testRedis() {
        try {
            redisTemplate.opsForValue().set("key", "value");
            String value = redisTemplate.opsForValue().get("key");
            return "Redis работает!\n" + "value = " + value;
        } catch (Exception e) {
            return "Ошибка подключения: " + e.getMessage();
        }
    }

    @PostMapping("/kafka")
    public String sendMessageToKafka()
    {
        throw new NotImplementedException("");
    }

}
